version: "3.8"
services:
  postgresql:
    image: postgres:alpine
    networks:
      - cm-network
    ports:
      - target: 5432 #needed for the backend to be able to access the db when querying
        published: 5431
    secrets:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    environment:
      # https://hub.docker.com/_/postgres
      - POSTGRES_DB_FILE=/run/secrets/POSTGRES_DB
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD

secrets:
  POSTGRES_DB:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true

networks:
  cm-network: